# Generated by Django 4.2.11 on 2024-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт'),
        ),
    ]
