site_name: My Docs
dev_addr: 127.0.0.1:8080

nav:
  - HTMLs:
      -"AllRaceResults": html/allraceresults.md
      -"Base": html/base.md
      -"comments": html/comments.md
      -"Login": html/login.md
      -"Profile": html/profile.md
      -"RaceDetails": html/race_detail.md
      -"RacerRegistration": html/racerregistration.md
      -"Register": html/register.md
      -"Tablo": html/tablo.md
      -"UserRegistration": html/userregistration.md

  - Main:
      - "CustomFilters": customfilters.md
      - "Admin": admin.md
      - "Apps": apps.md
      - "Forms": forms.md
      - "Models": models.md
      - "Urls": urls.md
      - "Views": views.md

